### ISSUE TITLE
US # <0011> *-App-Movil-QR 

### ISSUE THREAD

**Issue by Fabiricu** [practicaproISPC/grupo-7-g7#11]
•Como Director del Centro Medico quiero que los pacientes o usuarios puedan tener una aplicación desde sus dispositivos móviles, para escanear códigos QR y de esa manera, a través del sistema , puedan interactuar desde nuestro sistema web para solicitar un turno al especialista correspondiente.

**Comment by gabiervaz** [comment]
damos el fácil acceso al usuario a través del  codigo Qr
