### ISSUE TITLE
US # <0016> * -Diseño de la Pantalla Principal de la APP  

### ISSUE THREAD

**Issue by jofaro** [practicaproISPC/grupo-7-g7#17]
Comenzamos con el desarrollo en Plataforma HTML del diseño de pantalla principal.
En esta pantalla deberán estar incluidos los Botones de Inicio de Sesión.
Al ingresar direcciona al menú  de opciones. 
Incluir el Botón de Salida o cierre de sesión

**Comment by Fabiricu** [comment]
Se define en la pantalla principal con un color de fondo y el logo del sistema y también una ventana de acceso a Login para poder acceder al mismo

**Comment by gabiervaz** [comment]
los botones serán la parte fundamental para el manejo de la aplicación y serán quienes  guiarán al usuario a distintas acciones .

**Comment by dariocaminos** [comment]
Desde la ventana de ingreso o login, el usuario se podrá registrar o ingresar al sistema de turnos.
