### ISSUE TITLE
US # <0017> * - Pantallas Secundarias

### ISSUE THREAD

**Issue by jofaro** [practicaproISPC/grupo-7-g7#18]
Inicio del desarrollo en plataforma HTML de las pantallas secundarias de la APP.
Al hacer Clic en cada Opción del Menú debe direccionar a la pantalla correspondiente. aunque esté vacía y solo  muestre el tílulo x ahora.

**Comment by Fabiricu** [comment]
Crear un botón para poder solicitar , confirmar ,modificar o cancelar un turno.

**Comment by gabiervaz** [comment]
aquí encontraras un botón que el cual te redireccionará a la pagina de contactos.

**Comment by dariocaminos** [comment]
Crear un botón para cerrar la sesión del usuario y salir del sistema.
