### ISSUE TITLE
US # <0018> * - Creación de una carpeta Virtual o Depósito

### ISSUE THREAD

**Issue by jofaro** [practicaproISPC/grupo-7-g7#19]
Con la finalidad de compartir el código y la cdocumentación del desarrollo de la app  se crea este medio compartido en Google Drive con acceso para todos los integrantes del grupo. 
Propongo un trabajo colaborativo con Apuntes de la Documentación modificada o nueva, en los comentarios de este Issue.

**Comment by jofaro** [comment]
Gracias Darío. 
Listo el compartido...

https://drive.google.com/drive/folders/1mR2FUxwS_IlDn2nRs9QXWiw8EzVF1681?usp=sharing

**Comment by jofaro** [comment]
Clonar  esta carpeta con el proyecto.

**Comment by Fabiricu** [comment]
Se creo una carpeta online en el cual se procedió a realizar el trabajo colaborativo entre los integrantes del grupo.

**Comment by gabiervaz** [comment]
aquí se  encuentre toda la información y acciones de realizadas por todos los creadores de la app
