### ISSUE TITLE
US # <0021> Consultas dentro del sistema de bases de datos

### ISSUE THREAD

**Issue by Fabiricu** [practicaproISPC/grupo-7-g7#32]
Se realizaran consultas a aquellos usuarios debidamente registrados, y que sean usuarios permanentes, para que, una vez efectuada su alta y otorgandole un turno, pueda acceder a otra categoria de usuario, se le pueda realizar una historia clinica con todo su historial medico, y con la firma de los profesionales actuantes.

**Comment by gabiervaz** [comment]
aquí los desarrolladores podrán consultar  por datos ya sea con falencias o datos necesarios , como así también en su mantenimiento .
