### ISSUE TITLE
Titulo del Proyecto

### ISSUE THREAD

**Issue by jofaro** [practicaproISPC/grupo-7-g7#7]
Se trata de definir un nombre que le de identidad  a la aplicación.

**Comment by dariocaminos** [comment]
El nombre del proyecto creo que debería contener la palabra "Online"

**Comment by jofaro** [comment]
Excelente.  También debe tener un nombre relacionado con la Función

**Comment by gabiervaz** [comment]
me parece excelente , un nombre bien relacionado con el proyecto

**Comment by Fabiricu** [comment]
Un nombre que genera identidad al sitio, que lo diferencia de otros sitios relacionados, pero que le da una impronta de creatividad y dinamismo

**Comment by gabiervaz** [comment]
el nombre TuVi me parece muy bueno para el logo

**Comment by jofaro** [comment]
si estamos todos de acuerdo el nombre de la App será

"TuVi On Line"

**Comment by gabiervaz** [comment]
Excelente!!!!

**Comment by Fabiricu** [comment]
Genial, estoy de acuerdo con el nombre de la app!!
